# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hpothes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Protocole(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1224, 699)
        Form.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 650, 148, 35))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1030, 650, 148, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 1231, 91))
        self.label_8.setStyleSheet("background-color :rgb(180, 223, 255)")
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1030, 190, 161, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(1030, 250, 161, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 110, 531, 41))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(60, 190, 931, 400))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 223, 255))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 223, 255))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 223, 255))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Poppins SemiBold")
        font.setPointSize(10)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 223, 255))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget.setColumnWidth(2, 320)
        self.tableWidget.setColumnWidth(1, 110)
        self.tableWidget.setColumnWidth(0, 250)
        self.pushButton_3.clicked.connect(self._addRow)
        self.pushButton_4.clicked.connect(self._removeRow)
        f = open ("button.css","r")
        cssb = f.read()
        f.close()
        self.pushButton.setStyleSheet(cssb)
        self.pushButton_2.setStyleSheet(cssb)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    

    def _addRow(self) :
        rowCount = self.tableWidget.rowCount()
        self.tableWidget.insertRow(rowCount )
        combo =  QtWidgets.QComboBox()
        button = QtWidgets.QPushButton()
        combo.addItem('Vrai')
        combo.addItem('Faux')
        self.tableWidget.setCellWidget(rowCount, 1, combo)
        button.setText("Editer Actions")
        self.tableWidget.setCellWidget(rowCount, 3, button)
        
    def _removeRow(self):
        current = self.tableWidget.currentRow()
        if (current==-1) :
            if self.tableWidget.rowCount() > 0:
                self.tableWidget.removeRow(self.tableWidget.rowCount()-1)
        else :
            self.tableWidget.removeRow(current) 

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Retour"))
        self.pushButton_2.setText(_translate("Form", "Enregistrer"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">EDITEUR DE CAS MEDICAUX HIPPOCRATE</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "Ajouter un protocole"))
        self.pushButton_4.setText(_translate("Form", "Supprimer un protocole"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">Veuillez editer les protocoles</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Protocole"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Vrai / Faux"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Description"))
